<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendaftaran_model extends CI_Model
{

    public $table = 'pendaftaran';
    public $id = 'id_pendaftaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_komunitas()
    {
        $this->db->select('*');
        $this->db->from('pendaftaran');
        $this->db->join('penanaman', 'penanaman.nama_penanam = pendaftaran.id_pendaftaran');
        $this->db->join('users', 'users.id_user = penanaman.id_user');
        $query = $this->db->get();
        return $query->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

     function getkomunitas() {
        $data = array();
        $query = $this->db->get('pendaftaran');
        if ($query->num_rows() > 0) {
            foreach ($query->result_array() as $row){
                    $data[] = $row;
                }
        }
        $query->free_result();
        return $data;
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pendaftaran', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nama_komunitas', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('gambaran_komunitas', $q);
	$this->db->or_like('alasan', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('alamat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pendaftaran', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('nama_komunitas', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('gambaran_komunitas', $q);
	$this->db->or_like('alasan', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('alamat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        if ($this->db->query('SELECT nama_penanam from penanaman where nama_penanam = '.$id)->result_array()) {
            $this->session->set_flashdata('message', 'Tidak bisa dihapus');
        } else{
            $this->db->where($this->id, $id);
            $this->db->delete($this->table);    
            $this->session->set_flashdata('message', 'Hapus Sukses');
        }
    }

}

/* End of file Pendaftaran_model.php */
/* Location: ./application/models/Pendaftaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-24 19:12:53 */
/* http://harviacode.com */